### ISSUE TITLE
Get Adobe to add missing features

### ISSUE THREAD

**Issue by PrimaryFeather** [Gamua/Starling-Extension-Adobe-Animate#3]
The biggest problem with the "Texture Atlas" export in _Animate CC_ is that Adobe somehow stopped when it got interesting. In other words: the feature has great potential, but some small limitations make it really hard to use in a real project.

That's why we need to make our voice heard, and tell them what's missing! 

We can do that by using Adobe's feature request "wish form". The more developers tell them about the problems, the higher our chance to get this fixed. 

I'd appreciate your help with this! For this reason, I created a few copy/paste ready texts you can send to Adobe. To do this, follow these instructions:

1. Visit https://www.adobe.com/products/wishform.html
2. Choose "Adobe Animate CC" as the product.
3. You can use the following version data:
  * Product Version: Animate CC 2018
  * Build Version: 107
4. Add one of the title + description pairs from below.
5. Start again with the next pair.

Thanks a lot in advance, guys!

Here are the actual feature requests:

---

### Title

Texture Atlas Export: Add scale factors

### Description of your feature request:

Brief title for your desired feature:
Texture atas export: adding scale factors

How would you like the feature to work? 
In the export dialog, let the developer choose a set of scale factors, as it's typical nowadays for mobile development. The result should be that there are additional file pairs for sprite sheets (PNG + JSON).

Why is this feature important to you?
Because scale factors are a requirement for mobile and desktop development nowadays, and it's extremely cumbersome to export files without direct support in that "texture atlas" export dialog.

---

### Title

Texture Atlas Export: File size optimization

### Description of your feature request:

Brief title for your desired feature:
Texture Atlas Export: File size optimization

How would you like the feature to work? 

The "Animation.JSON" files that are created become really big quickly. Below are several ideas how you could optimize them.

* Remove 'DecomposedMatrix' — this information is redundant (can be calculated at runtime from the Matrix3D element). Furthermore, it sometimes decomposes the matrix to a 3D transformation even though a 2D transformation would do — wich makes the export data not usable in a pure 2D engine, anyway.
* Remove indentation (no more "prettified" JSON). The line breaks and indentation make up a huge part of the file size, actually. Add an option to optimize the JSON so that it skips all that.
* Optimize identical Frames. The algorithm sometimes does not recognize identical frames. Export a MovieClip with an empty layer (but several frames), and you'll see that each individual frame is listed with an empty "elements" array. Instead, one single frame should be repeated via the "duration".

Why is this feature important to you?
Because the exported JSON files become ridiculously big quickly.

---

### Title

Texture Atlas Export: more options for sprite sheets

### Description of your feature request:

Brief title for your desired feature:
Texture Atlas Export: more options for sprite sheets

How would you like the feature to work? 
* Skip Asset Collation: skip the spritemap generation altogether and export all textures to a folder in a high resolution. Developers can then just add these textures to their own sprite sheet software (like "TexturePacker"). Advantages: easy to integrate into any workflow, individual sprite sheets can be efficiently combined into one atlas with a separate tool; scale factor handling can be done by the developer.
* Don't force Power-of-Two Textures: on export, the spritemap is always extended to powers of two. Make this optional — most game engines can work well with non-POT-textures.

Why is this feature important to you?
Because the limiting export options for the sprite sheet make this otherwise great feature very difficult to integrate into custom workflows.

**Comment by sistr22** [comment]
I would argue that moving away from json and using flatbuffer to export the animation would lead to much, much smaller animation export. Personally I'm working on converting the json to a fatbuffer format to make the size of my game smaller.

**Comment by PrimaryFeather** [comment]
Apparently, Adobe has heard us and has implemented almost all of the changes that were asked for above. Thanks to everyone who forwarded those wishes to Adobe!

And, of course, a big thanks to Adobe for listening to us. That way, animations are much easier to integrate into typical game development workflows. :smile:

**Comment by PrimaryFeather** [comment]
Oh, here's the announcement of the changes in Adobe Animate 2019.2:
https://helpx.adobe.com/animate/using/whats-new/2019-2.html#Textureatlasenhancements
